### ISSUE TITLE
Web socket closes with code 1000 after stream of messages 

### ISSUE THREAD

**Issue by siegesmund** [tidwall/SwiftWebSocket#12]
When a large stream of messages takes longer than ~ 30 seconds to handle, after the last message is received, I get a socket closed message with a code 1000.

If I store the messages to an in-memory datastore, rather than on disk, this dramatically reduces the time it takes to process the messages (around 6 seconds), and this doesn't occur and the connection remains open, communicating normally.

Wondering if you know why this is happening and have any solutions for suggestions/workarounds?

**Comment by tidwall** [comment]
The library itself does not contain an explicit timeout. Code 1000 (Normal Closure) is the default code, leaving me to believe that the server or the client is closing the connection directly. 

Does it take 30 seconds to process one message in the large stream, or the entire stream?
Does your client code call the socket.close() method at any point?

**Comment by tidwall** [comment]
One more question.

Does your server send pings? 

SwiftWebSocket sends pongs immediately following a received ping. This happens automatically in the background and is not normally something your client code needs to worry about.

If your server sends a bunch of messages and then sends a ping somewhere along the line; and your client code takes a longer time than what the server expects before receiving the pong; then it's possible that the server is closing the connection.

For example, let's say that the server sends a ping every 30 seconds with the first ping occurring immediately after the connection opens. Following the first ping, the server sends 5 large messages. The client must handle each message through `event.message` in exact order prior to SwiftWebSocket responding with a pong.

But if it take more than 30 seconds to handle those 5 messages, then the server won't receive the pong prior to sending the next ping. This may cause the server to think that the client is not responding and explicitly close the connection.

If this happens to be cause of the issue, I suggest that rather than processing the message in it's entirety from inside the `event.message`; just send the message into a background `NSOperationQueue` (or some type of background thread) and do the processing of the message there. This will free up the websocket to return pongs and continue to run smoothly, but at the expense of having to temporary store messages in-memory.

**Comment by siegesmund** [comment]
To answer the first question, it takes ~ 30 seconds to process the stream, not a single large message. Your second suggestion was one of my hunches also, so it's good to hear you second it. I'll spend some time today on this, and will close the issue if this solves it. Thanks for the insightful response!

**Comment by siegesmund** [comment]
I put the messages into a background thread, and this seems to have solved the problem. Thanks -

**Comment by IVYcomptech** [comment]
> I put the messages into a background thread, and this seems to have solved the problem. Thanks -

Can you explain How you configured the messages background thread.
