### ISSUE TITLE
WatchOS support

### ISSUE THREAD

**Issue by Dev1an** [tidwall/SwiftWebSocket#45]
Why is WatchOS not supported? Are there any limitations on WatchOS that prevent us from using web sockets on the Apple Watch?

**Comment by tidwall** [comment]
AFAIK, WatchOS can't be supported because the watch does not allow for persistent network connections. 

It seems that custom socket connections are not allowed on the device. I ran across this discussion months ago, which applies to Watch OS 2

https://forums.developer.apple.com/thread/19399

SwiftWebSocket uses NSStream to establish a connection. Using NSStream is prohibited on the device but not in the simulator.

As I understand it the only way to communicate messages between the Watch and iPhone is with WSSession, and without the phone there is no guaranteed way for the Watch to have a persistent connection to a network.

I currently suspect the problem is specifically in the CFStreamCreatePairWithSocketToHost() call, which is not documented as being NOT supported on WatchOS.

https://forums.developer.apple.com/thread/5939
http://stackoverflow.com/questions/33367222/socket-connection-from-watchos-2-and-cfstream

From the first link above, an Apple rep says:

"You have a couple of options here:
- reformulate your networking in terms of NSURLSession
- if that’s not possible (say, you’re talking to a server that requires a custom TCP-based protocol), do that work on the iPhone"

The NSURLSession is not an option with WebSockets, and doing work on the iPhone defeats the purpose of having a standalone Watch app with persistent connection.

WebSockets are only HTTP for the initial handshake, after that they go into a raw byte stream mode. I suspect that Apple only allows HTTP through NSURL related calls (which cannot be used for WebSockets), and that these calls are simple wrappers around and underlying Wi-Fi or Bluetooth connection. But it's left as a blackbox to the developer.

I hope this information is helpful and I'd love to be wrong about this. If you know a solution please advise.
